version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    links:
      - database
    volumes:
      - .:/home/app
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=CorvusDDoSKrom
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: