version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "4000:4000"
    links:
      - bd
  bd:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=CorvusDDoSKrom
    volumes:
      - mysql:/var/lib/mysql
volumes:
  app-data: